import * as THREE from './vendor/three.module.js';
import {floors,floorById,colors,world,nodes} from './building.js';
const pointInside=(p,poly)=>{let yes=false;for(let i=0,j=poly.length-1;i<poly.length;j=i++){const a=poly[i],b=poly[j];if((a[1]>p[1])!==(b[1]>p[1])&&p[0]<(b[0]-a[0])*(p[1]-a[1])/(b[1]-a[1])+a[0])yes=!yes;}return yes;};
export class BuildingViewer{
 constructor(el,onMove,onElevator){this.el=el;this.onMove=onMove;this.onElevator=onElevator;this.floor=1;this.view='route';this.mode='overview';this.yaw=0;this.pitch=0;this.angle=.4;this.zoom=1;this.keys=new Set();this.groups=[];this.routeFloors=new Set([1,2]);this.scene=new THREE.Scene();this.scene.background=new THREE.Color('#102b3c');this.camera=new THREE.PerspectiveCamera(45,1,.1,600);this.renderer=new THREE.WebGLRenderer({antialias:true,preserveDrawingBuffer:true});this.renderer.setPixelRatio(Math.min(devicePixelRatio,2));this.renderer.outputColorSpace=THREE.SRGBColorSpace;el.appendChild(this.renderer.domElement);this.scene.add(new THREE.HemisphereLight('#e9f5ff','#4b657c',2.5));const light=new THREE.DirectionalLight('#fff3dc',2.3);light.position.set(-20,90,40);this.scene.add(light);this.base=new THREE.GridHelper(180,45,'#34566b','#1c3d50');this.base.position.set(8,-5,-10);this.scene.add(this.base);this.routeGroup=new THREE.Group();this.scene.add(this.routeGroup);
 for(const f of floors)this.makeFloor(f);this.makeAvatar();this.pos=new THREE.Vector3(...nodes.entrance.p);this.bindControls();new ResizeObserver(()=>this.resize()).observe(el);this.resize();this.updateVisibility();}
 makeShape(f,poly){let shape=new THREE.Shape();poly.forEach((p,i)=>{let w=world(f.id,p);i?shape.lineTo(w[0],-w[2]):shape.moveTo(w[0],-w[2]);});shape.closePath();return shape;}
 solid(f,poly,height,color,group,y=0,holes=[]){const shape=this.makeShape(f,poly);for(const h of holes){let path=new THREE.Path();h.forEach((p,i)=>{let w=world(f.id,p);i?path.lineTo(w[0],-w[2]):path.moveTo(w[0],-w[2]);});path.closePath();shape.holes.push(path);}let geometry=new THREE.ExtrudeGeometry(shape,{depth:height,bevelEnabled:false});geometry.rotateX(-Math.PI/2);const m=new THREE.Mesh(geometry,new THREE.MeshStandardMaterial({color,roughness:.85}));m.position.y=y;group.add(m);return m;}
 wall(f,a,b,h,color,group){let p=world(f.id,a),q=world(f.id,b),len=Math.hypot(q[0]-p[0],q[2]-p[2]);let m=new THREE.Mesh(new THREE.BoxGeometry(len,h,.09),new THREE.MeshStandardMaterial({color}));m.position.set((p[0]+q[0])/2,h/2,(p[2]+q[2])/2);m.rotation.y=-Math.atan2(q[2]-p[2],q[0]-p[0]);group.add(m);}
 tag(text,x,y,z,width,group,color='#173b50'){let canvas=document.createElement('canvas');canvas.width=768;canvas.height=112;let c=canvas.getContext('2d');c.fillStyle=color;c.roundRect(0,0,768,112,12);c.fill();c.fillStyle='white';c.font='bold 43px Arial';c.textAlign='center';c.fillText(text,384,73);let s=new THREE.Sprite(new THREE.SpriteMaterial({map:new THREE.CanvasTexture(canvas),depthTest:false}));s.position.set(x,y,z);s.scale.set(width,width*112/768,1);group.add(s);return s;}
 makeFloor(f){let group=new THREE.Group();group.position.y=(f.id-1)*4.5;group.userData.floor=f.id;this.scene.add(group);this.groups.push(group);this.solid(f,f.outline,.18,'#b5cbd6',group,-.2,f.holes);for(let i=0;i<f.outline.length;i++)this.wall(f,f.outline[i],f.outline[(i+1)%f.outline.length],.6,'#7999ab',group);for(const h of f.holes)for(let i=0;i<h.length;i++)this.wall(f,h[i],h[(i+1)%h.length],.65,'#dfedf2',group);
 for(const room of f.rooms){this.solid(f,room.poly,.08,colors[room.type],group,.01);for(let i=0;i<room.poly.length;i++){// Cutaway low walls keep reference layouts readable.
 this.wall(f,room.poly[i],room.poly[(i+1)%room.poly.length],room.type==='service'?1.3:.8,room.type==='service'?'#5a6d82':'#c8dae3',group);}
 let cx=room.poly.reduce((v,p)=>v+p[0],0)/room.poly.length,cy=room.poly.reduce((v,p)=>v+p[1],0)/room.poly.length,[x,,z]=world(f.id,[cx,cy]);let t=this.tag(room.id,x,1.25,z,Math.min(7,Math.max(2.2,room.id.length*.32)),group,room.type==='classroom'?'#225d76':room.type==='meeting'?'#67448d':'#344e60');t.userData.roomLabel=true;}
 // The three-car bank is represented together; car dimensions are illustrative.
 const origin=world(f.id,f.anchor);for(let i=0;i<3;i++){let x=origin[0]+(i-1)*1.7,z=origin[2]+(i-1)*1.2;let cab=new THREE.Mesh(new THREE.BoxGeometry(1.5,2.6,1.4),new THREE.MeshStandardMaterial({color:'#769e99',transparent:true,opacity:.65}));cab.position.set(x,1.3,z);cab.rotation.y=-.63;group.add(cab);this.tag(String(i+1),x,3,z,1.5,group,'#216d58');}
 for(const [sx,sy]of f.stairs){const [x,,z]=world(f.id,[sx,sy]);for(let j=0;j<9;j++){let step=new THREE.Mesh(new THREE.BoxGeometry(1.7,.15,.3),new THREE.MeshStandardMaterial({color:'#d99255'}));step.position.set(x,.08+j*.15,z-j*.3);group.add(step);}}
 let bb=new THREE.Box3().setFromObject(group);this.tag(f.id===0?'B · GARDEN LEVEL':'FLOOR '+f.id,bb.min.x-4,1,(bb.min.z+bb.max.z)/2,6,group,'#24495f');
 }
 makeAvatar(){this.avatar=new THREE.Group();const mat=new THREE.MeshStandardMaterial({color:'#36edbd'});let body=new THREE.Mesh(new THREE.CapsuleGeometry(.22,.5,5,10),mat);body.position.y=.8;this.avatar.add(body);let head=new THREE.Mesh(new THREE.SphereGeometry(.21,16,12),new THREE.MeshStandardMaterial({color:'#ddfff2'}));head.position.y=1.35;this.avatar.add(head);for(const x of [-.35,.35]){const wheel=new THREE.Mesh(new THREE.TorusGeometry(.3,.05,8,20),new THREE.MeshStandardMaterial({color:'#0d2838'}));wheel.position.set(x,.35,0);wheel.rotation.y=Math.PI/2;wheel.name='wheel';this.avatar.add(wheel);}const ring=new THREE.Mesh(new THREE.RingGeometry(.5,.7,32),new THREE.MeshBasicMaterial({color:'#59ffcb',side:THREE.DoubleSide}));ring.rotation.x=-Math.PI/2;ring.position.y=.15;this.avatar.add(ring);this.scene.add(this.avatar);}
 setRoute(path){this.path=path;this.routeFloors=new Set(path.map(k=>nodes[k].floor));if(!path.length)this.routeFloors=new Set([this.floor]);for(const m of [...this.routeGroup.children]){this.routeGroup.remove(m);m.geometry.dispose();m.material.dispose();}path.slice(1).forEach((id,i)=>{let a=new THREE.Vector3(...nodes[path[i]].p),b=new THREE.Vector3(...nodes[id].p);a.y+=.22;b.y+=.22;const m=new THREE.Mesh(new THREE.CylinderGeometry(.085,.085,a.distanceTo(b),9),new THREE.MeshBasicMaterial({color:'#56ffd0',depthTest:false}));m.position.copy(a).add(b).multiplyScalar(.5);m.quaternion.setFromUnitVectors(new THREE.Vector3(0,1,0),b.clone().sub(a).normalize());m.userData.floors=[nodes[path[i]].floor,nodes[id].floor];m.renderOrder=8;this.routeGroup.add(m);});this.updateVisibility();}
 updateVisibility(){for(const g of this.groups){let f=g.userData.floor;g.visible=this.mode!=='overview'?f===this.floor:this.view==='all'||this.view==='route'&&this.routeFloors.has(f)||Number(this.view)===f;g.position.y=(f-1)*4.5+(this.mode==='overview'&&this.view==='all'?f*4:0);g.children.forEach(m=>{if(m.userData.roomLabel)m.visible=this.mode==='overview'&&this.view!=='all';});}this.routeGroup.visible=this.view!=='all'||this.mode!=='overview';this.routeGroup.children.forEach(m=>{let f=m.userData.floors;m.visible=this.mode==='overview'||f.includes(this.floor);});this.avatar.visible=this.mode!=='pov'&&this.mode!=='manual';}
 setMode(mode){this.mode=mode;this.keys.clear();this.updateVisibility();if(mode==='manual'){this.yaw=0;this.pitch=0;this.renderer.domElement.focus();}}
 setPosition(p){this.pos.set(...p);this.floor=Math.round(p[1]/4.5)+1;this.floor=Math.max(0,Math.min(7,this.floor));this.updateVisibility();}
 useElevator(f){const p=nodes['e'+f].p;this.setPosition(p);this.onMove(this.pos.toArray(),f);}
 nearElevator(){const p=nodes['e'+this.floor].p;return Math.hypot(this.pos.x-p[0],this.pos.z-p[2])<4;}
 allowed(x,z){let f=floorById[this.floor],p=[x/f.scale+f.anchor[0],z/f.scale+f.anchor[1]];if(!pointInside(p,f.outline))return false;if(f.holes.some(h=>pointInside(p,h)))return false;return !f.rooms.some(r=>pointInside(p,r.poly));}
 bindControls(){const canvas=this.renderer.domElement;canvas.tabIndex=0;canvas.setAttribute('aria-label','3D building. In keyboard mode use W A S D or arrow keys. Drag to look. E opens the elevator near its lobby.');let dragging=false,lastX=0,lastY=0;canvas.addEventListener('pointerdown',e=>{dragging=true;lastX=e.clientX;lastY=e.clientY;canvas.setPointerCapture(e.pointerId);canvas.focus();});canvas.addEventListener('pointermove',e=>{if(!dragging)return;let dx=e.clientX-lastX,dy=e.clientY-lastY;if(this.mode==='overview')this.angle+=dx*.006;else{this.yaw-=dx*.004;this.pitch=Math.max(-.8,Math.min(.8,this.pitch-dy*.003));}lastX=e.clientX;lastY=e.clientY;});canvas.addEventListener('pointerup',()=>dragging=false);canvas.addEventListener('wheel',e=>{if(this.mode==='overview'){e.preventDefault();this.zoom=Math.max(.5,Math.min(1.8,this.zoom+e.deltaY*.001));}},{passive:false});canvas.addEventListener('keydown',e=>{if(this.mode!=='manual')return;let key=e.key.toLowerCase();if(['w','a','s','d','arrowup','arrowdown','arrowleft','arrowright','e','q','r','escape'].includes(key)){e.preventDefault();this.keys.add(key);if(!e.repeat&&['w','a','s','d','arrowup','arrowdown','arrowleft','arrowright'].includes(key))this.tick(.06,'wheelchair');if(key==='e'&&!e.repeat)this.onElevator(this.nearElevator());}});canvas.addEventListener('keyup',e=>this.keys.delete(e.key.toLowerCase()));canvas.addEventListener('blur',()=>this.keys.clear());window.addEventListener('blur',()=>this.keys.clear());}
 resize(){let w=this.el.clientWidth,h=this.el.clientHeight;if(w&&h){this.renderer.setSize(w,h);this.camera.aspect=w/h;this.camera.updateProjectionMatrix();}}
 tick(dt,profile){if(this.mode==='manual'){const k=this.keys;let forward=(k.has('w')||k.has('arrowup')?1:0)-(k.has('s')||k.has('arrowdown')?1:0),right=(k.has('d')||k.has('arrowright')?1:0)-(k.has('a')||k.has('arrowleft')?1:0);if(k.has('q'))this.yaw+=dt*1.6;if(k.has('r'))this.yaw-=dt*1.6;let length=Math.hypot(forward,right)||1,speed=dt*3/length,dx=(-Math.sin(this.yaw)*forward+Math.cos(this.yaw)*right)*speed,dz=(-Math.cos(this.yaw)*forward-Math.sin(this.yaw)*right)*speed;if(this.allowed(this.pos.x+dx,this.pos.z))this.pos.x+=dx;if(this.allowed(this.pos.x,this.pos.z+dz))this.pos.z+=dz;if(forward||right)this.onMove(this.pos.toArray(),this.floor);}
 this.avatar.position.copy(this.pos);this.avatar.children.filter(x=>x.name==='wheel').forEach(x=>x.visible=profile!=='walking');if(this.mode==='overview'){let all=this.view==='all',r=(all?125:88)*this.zoom,centerY=all?23:Math.max(0,(Number(this.view)||Math.max(...this.routeFloors))-1)*3;this.camera.position.set(Math.sin(this.angle)*r,centerY+(all?65:58)*this.zoom,Math.cos(this.angle)*r-10);this.camera.lookAt(8,centerY,-7);}else{let eye=profile==='wheelchair'?1.15:1.65;this.camera.position.copy(this.pos).add(new THREE.Vector3(0,eye,0));if(this.mode==='pov'&&this.path?.length){let next=this.path.find(k=>new THREE.Vector3(...nodes[k].p).distanceTo(this.pos)>1.5);/* heading is supplied by setHeading during autoplay */}let dir=new THREE.Vector3(-Math.sin(this.yaw)*Math.cos(this.pitch),Math.sin(this.pitch),-Math.cos(this.yaw)*Math.cos(this.pitch));this.camera.lookAt(this.camera.position.clone().add(dir));}this.renderer.render(this.scene,this.camera);}
 setHeading(a,b){if(this.mode==='pov'&&Math.hypot(b[0]-a[0],b[2]-a[2])>.01)this.yaw=Math.atan2(-(b[0]-a[0]),-(b[2]-a[2]));}
}
