import * as THREE from './vendor/three.module.js';
import {floors,floorById,world,nodes,sourceAllowed,obstacle} from './active-building.js';
const pointInside=(p,poly)=>{let yes=false;for(let i=0,j=poly.length-1;i<poly.length;j=i++){const a=poly[i],b=poly[j];if((a[1]>p[1])!==(b[1]>p[1])&&p[0]<(b[0]-a[0])*(p[1]-a[1])/(b[1]-a[1])+a[0])yes=!yes;}return yes;};
export class BuildingViewer{
 constructor(el,onMove,onElevator){this.el=el;this.onMove=onMove;this.onElevator=onElevator;this.floor=1;this.view='route';this.mode='overview';this.yaw=0;this.pitch=0;this.angle=.4;this.zoom=1;this.keys=new Set();this.groups=[];this.routeFloors=new Set([1,2]);this.scene=new THREE.Scene();this.scene.background=new THREE.Color('#090909');this.camera=new THREE.PerspectiveCamera(45,1,.1,600);this.renderer=new THREE.WebGLRenderer({antialias:true,preserveDrawingBuffer:true});this.renderer.setPixelRatio(Math.min(devicePixelRatio,2));this.renderer.outputColorSpace=THREE.SRGBColorSpace;this.renderer.toneMapping=THREE.ACESFilmicToneMapping;this.renderer.toneMappingExposure=1.1;this.scene.fog=new THREE.Fog('#090909',70,210);el.appendChild(this.renderer.domElement);this.minimap=document.createElement('div');this.minimap.className='indoor-minimap';this.minimap.setAttribute('aria-label','Current floor and position');el.appendChild(this.minimap);this.scene.add(new THREE.HemisphereLight('#f5f5f2','#181818',2.6));const light=new THREE.DirectionalLight('#ffe082',2.2);light.position.set(-20,90,40);this.scene.add(light);this.base=new THREE.GridHelper(180,45,'#383838','#181818');this.base.position.set(8,-5,-10);this.scene.add(this.base);this.routeGroup=new THREE.Group();this.scene.add(this.routeGroup);
 for(const f of floors)this.makeFloor(f);this.blockMesh=new THREE.Mesh(new THREE.BoxGeometry(1.4,1.2,1.4),new THREE.MeshStandardMaterial({color:'#ff9152'}));this.blockMesh.visible=false;this.scene.add(this.blockMesh);this.makeAvatar();this.pos=new THREE.Vector3(...nodes.entrance.p);this.bindControls();new ResizeObserver(()=>this.resize()).observe(el);this.resize();this.updateVisibility();}
 makeShape(f,poly){let shape=new THREE.Shape();poly.forEach((p,i)=>{let w=world(f.id,p);i?shape.lineTo(w[0],-w[2]):shape.moveTo(w[0],-w[2]);});shape.closePath();return shape;}
 solid(f,poly,height,color,group,y=0,holes=[]){const shape=this.makeShape(f,poly);for(const h of holes){let path=new THREE.Path();h.forEach((p,i)=>{let w=world(f.id,p);i?path.lineTo(w[0],-w[2]):path.moveTo(w[0],-w[2]);});path.closePath();shape.holes.push(path);}let geometry=new THREE.ExtrudeGeometry(shape,{depth:height,bevelEnabled:false});geometry.rotateX(-Math.PI/2);const m=new THREE.Mesh(geometry,new THREE.MeshStandardMaterial({color,roughness:.85}));m.position.y=y;group.add(m);return m;}
 wall(f,a,b,h,color,group){let p=world(f.id,a),q=world(f.id,b),len=Math.hypot(q[0]-p[0],q[2]-p[2]);let m=new THREE.Mesh(new THREE.BoxGeometry(len,h,.09),new THREE.MeshStandardMaterial({color}));m.position.set((p[0]+q[0])/2,h/2,(p[2]+q[2])/2);m.rotation.y=-Math.atan2(q[2]-p[2],q[0]-p[0]);m.userData.wall=true;m.userData.height=h;group.add(m);}
 tag(text,x,y,z,width,group,color='#181818'){let canvas=document.createElement('canvas');canvas.width=768;canvas.height=112;let c=canvas.getContext('2d');c.fillStyle=color;c.roundRect(0,0,768,112,12);c.fill();c.fillStyle='white';c.font='bold 43px Arial';c.textAlign='center';c.fillText(text,384,73);let s=new THREE.Sprite(new THREE.SpriteMaterial({map:new THREE.CanvasTexture(canvas),depthTest:false}));s.position.set(x,y,z);s.scale.set(width,width*112/768,1);group.add(s);return s;}
 makeFloor(f){if(f.source)return this.makeSourceFloor(f);let group=new THREE.Group();group.position.y=(f.id-1)*4.5;group.userData.floor=f.id;this.scene.add(group);this.groups.push(group);this.solid(f,f.outline,.18,'#202020',group,-.2,f.holes);for(let i=0;i<f.outline.length;i++)this.wall(f,f.outline[i],f.outline[(i+1)%f.outline.length],.6,'#444444',group);for(const h of f.holes)for(let i=0;i<h.length;i++)this.wall(f,h[i],h[(i+1)%h.length],.65,'#dfedf2',group);
 for(const room of f.rooms){this.solid(f,room.poly,.08,'#242424',group,.01);for(let i=0;i<room.poly.length;i++){// Cutaway low walls keep reference layouts readable.
 this.wall(f,room.poly[i],room.poly[(i+1)%room.poly.length],room.type==='service'?1.3:.8,room.type==='service'?'#708b91':'#edece7',group);}
 let cx=room.poly.reduce((v,p)=>v+p[0],0)/room.poly.length,cy=room.poly.reduce((v,p)=>v+p[1],0)/room.poly.length,[x,,z]=world(f.id,[cx,cy]);let t=this.tag(room.id,x,1.25,z,Math.min(7,Math.max(2.2,room.id.length*.32)),group,room.type==='classroom'?'#3a2a5e':room.type==='meeting'?'#5b3a86':'#181818');t.userData.roomLabel=true;}
 // The three-car bank is represented together; car dimensions are illustrative.
 const origin=world(f.id,f.anchor);for(let i=0;i<3;i++){let x=origin[0]+(i-1)*1.7,z=origin[2]+(i-1)*1.2;let cab=new THREE.Mesh(new THREE.BoxGeometry(1.5,2.6,1.4),new THREE.MeshStandardMaterial({color:'#4a4a4a',transparent:true,opacity:.65}));cab.position.set(x,1.3,z);cab.rotation.y=-.63;group.add(cab);this.tag(String(i+1),x,3,z,1.5,group,'#9b7a18');}
 for(const [sx,sy]of f.stairs){const [x,,z]=world(f.id,[sx,sy]);for(let j=0;j<9;j++){let step=new THREE.Mesh(new THREE.BoxGeometry(1.7,.15,.3),new THREE.MeshStandardMaterial({color:'#ff9152'}));step.position.set(x,.08+j*.15,z-j*.3);group.add(step);}}
 let bb=new THREE.Box3().setFromObject(group);this.tag(f.id===0?'B · GARDEN LEVEL':'FLOOR '+f.id,bb.min.x-4,1,(bb.min.z+bb.max.z)/2,6,group,'#24495f');
 }
 makeSourceFloor(f){const group=new THREE.Group();group.userData.floor=f.id;group.position.y=(f.id-1)*4.5;this.groups.push(group);this.scene.add(group);const mesh=f.mesh,dummy=new THREE.Object3D();const slab=new THREE.InstancedMesh(new THREE.BoxGeometry(1,1,1),new THREE.MeshStandardMaterial({color:'#202020'}),mesh.slabs.length);mesh.slabs.forEach((q,i)=>{dummy.position.set(q.x,-.1,q.z);dummy.scale.set(q.width,.2,q.depth+.005);dummy.rotation.set(0,0,0);dummy.updateMatrix();slab.setMatrixAt(i,dummy.matrix);});group.add(slab);
 for(const [a,b] of mesh.walls){const len=Math.hypot(b[0]-a[0],b[1]-a[1]),m=new THREE.Mesh(new THREE.BoxGeometry(len,.7,.12),new THREE.MeshStandardMaterial({color:'#444444'}));m.position.set((a[0]+b[0])/2,.35,(a[1]+b[1])/2);m.rotation.y=-Math.atan2(b[1]-a[1],b[0]-a[0]);m.userData={wall:true,height:.7};group.add(m);}
 for(const room of f.source.rooms){const [x,,z]=world(f.id,room.point);const marker=new THREE.Mesh(new THREE.CylinderGeometry(.45,.45,.08,16),new THREE.MeshStandardMaterial({color:colors.library}));marker.position.set(x,.05,z);group.add(marker);const t=this.tag(room.label,x,1.25,z,Math.min(8,Math.max(3,room.label.length*.16)),group,'#181818');t.userData.roomLabel=true;}
 for(const p of f.source.lifts||[f.source.lift||f.source.spawn]){const [x,,z]=world(f.id,p);const color=f.source.liftInferred?'#c9913f':'#f4c542';for(const dx of [-.8,.8]){const m=new THREE.Mesh(new THREE.BoxGeometry(.12,2.6,.15),new THREE.MeshStandardMaterial({color}));m.position.set(x+dx,1.3,z);group.add(m);}this.tag(f.source.liftInferred?'Lift · inferred':'Elevator',x,3,z,3,group,'#9b7a18');}
 if(f.source.stairs){const [x,,z]=world(f.id,f.source.stairs);for(let j=0;j<8;j++){const step=new THREE.Mesh(new THREE.BoxGeometry(1.5,.15,.3),new THREE.MeshStandardMaterial({color:'#ff9152'}));step.position.set(x,.08+j*.15,z-j*.3);group.add(step);}}
 }
 loadBuilding(){for(const g of this.groups){this.scene.remove(g);g.traverse(m=>{m.geometry?.dispose();const mats=Array.isArray(m.material)?m.material:[m.material];for(const mat of mats)if(mat){mat.map?.dispose();mat.dispose();}});}this.groups=[];for(const f of floors)this.makeFloor(f);this.keys.clear();this.setPosition(nodes.entrance.p);this.view=String(this.floor);this.zoom=1;this.setMode('overview');if(!this.blockMesh){this.blockMesh=new THREE.Mesh(new THREE.BoxGeometry(1.4,1.2,1.4),new THREE.MeshStandardMaterial({color:'#ff9152'}));this.scene.add(this.blockMesh);}this.updateVisibility();}
 makeAvatar(){this.avatar=new THREE.Group();const mat=new THREE.MeshStandardMaterial({color:'#f4c542'});let body=new THREE.Mesh(new THREE.CapsuleGeometry(.22,.5,5,10),mat);body.position.y=.8;this.avatar.add(body);let head=new THREE.Mesh(new THREE.SphereGeometry(.21,16,12),new THREE.MeshStandardMaterial({color:'#f5f5f2'}));head.position.y=1.35;this.avatar.add(head);for(const x of [-.35,.35]){const wheel=new THREE.Mesh(new THREE.TorusGeometry(.3,.05,8,20),new THREE.MeshStandardMaterial({color:'#090909'}));wheel.position.set(x,.35,0);wheel.rotation.y=Math.PI/2;wheel.name='wheel';this.avatar.add(wheel);}const ring=new THREE.Mesh(new THREE.RingGeometry(.5,.7,32),new THREE.MeshBasicMaterial({color:'#f4c542',side:THREE.DoubleSide}));ring.rotation.x=-Math.PI/2;ring.position.y=.15;this.avatar.add(ring);this.scene.add(this.avatar);}
 setRoute(path){this.path=path;this.routeFloors=new Set(path.map(k=>nodes[k].floor));if(!path.length)this.routeFloors=new Set([this.floor]);for(const m of [...this.routeGroup.children]){this.routeGroup.remove(m);m.geometry.dispose();m.material.dispose();}path.slice(1).forEach((id,i)=>{let a=new THREE.Vector3(...nodes[path[i]].p),b=new THREE.Vector3(...nodes[id].p);a.y+=.22;b.y+=.22;const m=new THREE.Mesh(new THREE.CylinderGeometry(.085,.085,a.distanceTo(b),9),new THREE.MeshBasicMaterial({color:'#f4c542',depthTest:false}));m.position.copy(a).add(b).multiplyScalar(.5);m.quaternion.setFromUnitVectors(new THREE.Vector3(0,1,0),b.clone().sub(a).normalize());m.userData.floors=[nodes[path[i]].floor,nodes[id].floor];m.renderOrder=8;this.routeGroup.add(m);});this.updateVisibility();}
 updateVisibility(){const gap=floors.length>1?Math.max(4,28/(floors.length-1)):0;for(const g of this.groups){let f=g.userData.floor,i=floors.findIndex(x=>x.id===f);g.visible=this.mode!=='overview'?f===this.floor:this.view==='all'||this.view==='route'&&this.routeFloors.has(f)||Number(this.view)===f;g.position.y=(f-1)*4.5+(this.mode==='overview'&&this.view==='all'?i*gap:0);g.children.forEach(m=>{if(m.userData.wall){let h=this.mode==='overview'?m.userData.height:2.8;m.scale.y=h/m.userData.height;m.position.y=h/2;}if(m.userData.roomLabel){m.visible=this.view!=='all'||this.mode!=='overview';m.position.y=this.mode==='overview'?1.25:3.15;}});}this.routeGroup.visible=this.view!=='all'||this.mode!=='overview';this.routeGroup.children.forEach(m=>{let f=m.userData.floors;m.visible=this.mode==='overview'?(this.view==='route'||this.view==='all'||f.includes(Number(this.view))):f.includes(this.floor);});this.avatar.visible=this.mode!=='pov'&&this.mode!=='manual';this.base.visible=false;}
 setMode(mode){this.mode=mode;this.keys.clear();this.updateVisibility();if(mode==='manual'){this.yaw=0;this.pitch=0;this.renderer.domElement.focus();}}
 setPosition(p){this.pos.set(...p);this.floor=Math.round(p[1]/4.5)+1;this.floor=Math.max(Math.min(...floors.map(f=>f.id)),Math.min(Math.max(...floors.map(f=>f.id)),this.floor));this.updateVisibility();}
 useElevator(f){const p=nodes['e'+f].p;this.setPosition(p);this.onMove(this.pos.toArray(),f);}
 nearElevator(){const candidates=Object.entries(nodes).filter(([id,n])=>/^e\d+(?:-1)?$/.test(id)&&n.floor===this.floor).sort((a,b)=>Math.hypot(this.pos.x-a[1].p[0],this.pos.z-a[1].p[2])-Math.hypot(this.pos.x-b[1].p[0],this.pos.z-b[1].p[2]));const near=candidates[0];this.liftIndex=near?.[0].endsWith('-1')?1:0;return !!near&&Math.hypot(this.pos.x-near[1].p[0],this.pos.z-near[1].p[2])<(floorById[this.floor].source?1.6:4);}
 allowed(x,z){if(obstacle&&obstacle.floor===this.floor&&Math.hypot(x-obstacle.p[0],z-obstacle.p[2])<obstacle.radius+.2)return false;let f=floorById[this.floor];if(!f)return false;if(f.source)return sourceAllowed(f,x,z);let p=[x/f.scale+f.anchor[0],z/f.scale+f.anchor[1]];if(!pointInside(p,f.outline))return false;if(f.holes.some(h=>pointInside(p,h)))return false;return !f.rooms.some(r=>pointInside(p,r.poly));}
 bindControls(){const canvas=this.renderer.domElement;canvas.tabIndex=0;canvas.setAttribute('aria-label','3D building. In keyboard mode use W A S D or arrow keys. Drag to look. E opens the elevator near its lobby.');let dragging=false,lastX=0,lastY=0;canvas.addEventListener('pointerdown',e=>{dragging=true;lastX=e.clientX;lastY=e.clientY;canvas.setPointerCapture(e.pointerId);canvas.focus();});canvas.addEventListener('pointermove',e=>{if(!dragging)return;let dx=e.clientX-lastX,dy=e.clientY-lastY;if(this.mode==='overview')this.angle+=dx*.006;else{this.yaw-=dx*.004;this.pitch=Math.max(-.8,Math.min(.8,this.pitch-dy*.003));}lastX=e.clientX;lastY=e.clientY;});canvas.addEventListener('pointerup',()=>dragging=false);canvas.addEventListener('wheel',e=>{if(this.mode==='overview'){e.preventDefault();this.zoom=Math.max(.5,Math.min(1.8,this.zoom+e.deltaY*.001));}},{passive:false});canvas.addEventListener('keydown',e=>{if(this.mode!=='manual')return;let key=e.key.toLowerCase();if(['w','a','s','d','arrowup','arrowdown','arrowleft','arrowright','e','q','r','escape'].includes(key)){e.preventDefault();this.keys.add(key);if(!e.repeat&&['w','a','s','d','arrowup','arrowdown','arrowleft','arrowright'].includes(key))this.tick(.06,'wheelchair');if(key==='e'&&!e.repeat)this.onElevator(this.nearElevator());}});canvas.addEventListener('keyup',e=>this.keys.delete(e.key.toLowerCase()));canvas.addEventListener('blur',()=>this.keys.clear());window.addEventListener('blur',()=>this.keys.clear());}
 resize(){let w=this.el.clientWidth,h=this.el.clientHeight;if(w&&h){this.renderer.setSize(w,h);this.camera.aspect=w/h;this.camera.updateProjectionMatrix();}}
 tick(dt,profile){this.mapClock=(this.mapClock||0)+dt;if(this.mapClock>.15){this.mapClock=0;this.updateMinimap();}if(this.blockMesh){this.blockMesh.visible=!!obstacle&&obstacle.floor===this.floor;if(obstacle)this.blockMesh.position.set(obstacle.p[0],obstacle.p[1]+.6,obstacle.p[2]);}if(this.mode==='manual'){const k=this.keys;let forward=(k.has('w')||k.has('arrowup')?1:0)-(k.has('s')||k.has('arrowdown')?1:0),right=(k.has('d')||k.has('arrowright')?1:0)-(k.has('a')||k.has('arrowleft')?1:0);if(k.has('q'))this.yaw+=dt*1.6;if(k.has('r'))this.yaw-=dt*1.6;let length=Math.hypot(forward,right)||1,speed=dt*3/length,dx=(-Math.sin(this.yaw)*forward+Math.cos(this.yaw)*right)*speed,dz=(-Math.cos(this.yaw)*forward-Math.sin(this.yaw)*right)*speed;const steps=Math.max(1,Math.ceil(Math.hypot(dx,dz)/.06));for(let i=0;i<steps;i++){if(this.allowed(this.pos.x+dx/steps,this.pos.z))this.pos.x+=dx/steps;if(this.allowed(this.pos.x,this.pos.z+dz/steps))this.pos.z+=dz/steps;}if(forward||right)this.onMove(this.pos.toArray(),this.floor);}
 this.avatar.position.copy(this.pos);this.avatar.children.filter(x=>x.name==='wheel').forEach(x=>x.visible=profile==='wheelchair');if(this.mode==='overview'){let all=this.view==='all',r=(all?125:88)*this.zoom,gap=floors.length>1?Math.max(4,28/(floors.length-1)):0,stack=floors.map((f,i)=>({y:(f.id-1)*4.5+i*gap,c:f.source?f.mesh.center:[8,-7]})),centerY=all?(Math.min(...stack.map(f=>f.y))+Math.max(...stack.map(f=>f.y)))/2:Math.max(0,(Number(this.view)||Math.max(...this.routeFloors))-1)*3,centerX=all?stack.reduce((sum,f)=>sum+f.c[0],0)/stack.length:8,centerZ=all?stack.reduce((sum,f)=>sum+f.c[1],0)/stack.length:-7;this.camera.position.set(centerX+Math.sin(this.angle)*r,centerY+(all?65:58)*this.zoom,centerZ+Math.cos(this.angle)*r);this.camera.lookAt(centerX,centerY,centerZ);const f=floorById[Number(this.view)]||floorById[this.floor];if(f?.source&&!all){const d=f.mesh.span,c=f.mesh.center,y=(f.id-1)*4.5;this.camera.position.set(c[0]+Math.sin(this.angle)*d*this.zoom,y+d*.72*this.zoom,c[1]+Math.cos(this.angle)*d*.7*this.zoom);this.camera.lookAt(c[0],y,c[1]);}}else{let eye=profile==='wheelchair'?1.15:1.65;this.camera.position.copy(this.pos).add(new THREE.Vector3(0,eye,0));if(this.mode==='pov'&&this.path?.length){let next=this.path.find(k=>new THREE.Vector3(...nodes[k].p).distanceTo(this.pos)>1.5);/* heading is supplied by setHeading during autoplay */}let dir=new THREE.Vector3(-Math.sin(this.yaw)*Math.cos(this.pitch),Math.sin(this.pitch),-Math.cos(this.yaw)*Math.cos(this.pitch));this.camera.lookAt(this.camera.position.clone().add(dir));}if(this.mode!=='overview')for(const g of this.groups)if(g.visible)for(const m of g.children)if(m.userData.roomLabel)m.visible=Math.hypot(m.position.x-this.pos.x,m.position.z-this.pos.z)<12;this.renderer.render(this.scene,this.camera);}
 updateMinimap(){this.minimap.hidden=this.mode==='overview';if(this.minimap.hidden)return;const f=floorById[this.floor];if(!f)return;const s=f.source,polys=s?s.zones:[f.outline],holes=s?s.exclusions:f.holes,all=polys.flat(),xs=all.map(p=>p[0]),ys=all.map(p=>p[1]),x=Math.min(...xs),y=Math.min(...ys),w=Math.max(...xs)-x,h=Math.max(...ys)-y;const pos=s?[this.pos.x/s.scale+s.width/2,this.pos.z/s.scale+s.height/2]:[this.pos.x/f.scale+f.anchor[0],this.pos.z/f.scale+f.anchor[1]];const polygon=(p,color)=>`<polygon points="${p.map(q=>q.join(',')).join(' ')}" fill="${color}"/>`;this.minimap.innerHTML=`<svg viewBox="${x-10} ${y-10} ${w+20} ${h+20}" role="img" aria-label="Position on current floor">${polys.map(p=>polygon(p,'#262626')).join('')}${holes.map(p=>polygon(p,'#090909')).join('')}${(s?[]:f.rooms.map(r=>r.poly)).map(p=>polygon(p,'#202020')).join('')}<circle cx="${pos[0]}" cy="${pos[1]}" r="${Math.max(w,h)*.022}" fill="#f4c542" stroke="#f5f5f2" stroke-width="${Math.max(w,h)*.005}"/></svg>`;}
 setHeading(a,b){if(this.mode==='pov'&&Math.hypot(b[0]-a[0],b[2]-a[2])>.01)this.yaw=Math.atan2(-(b[0]-a[0]),-(b[2]-a[2]));}
}
